trigger:
  branches:
    include:
      - refs/heads/latest
      - refs/heads/11.*
      - refs/heads/25.*

jobs:
- job: BuildDocs
  displayName: Build Docs
  pool: az-ubuntu-2404-builders 
  variables:
  - group: azure-secrets
  steps:
  - checkout: self
  - task: UsePythonVersion@0
    inputs:
      versionSpec: 3.x
  - script: |
      pip install pipenv
      pipenv install
      pipenv run sphinx-build -M html . build/
    displayName: Build Docs
  - publish: build
    artifact: micetro_docs
    displayName: Publish Docs
  - script: |
      ls $(Build.SourcesDirectory)
      sed -i 's/version/$(Build.SourceBranch)/g' $(Build.SourcesDirectory)/Dockerfile
    displayName: Prepare for docker build
  - task: Docker@2
    displayName: Login to ACR
    inputs:
      command: login
      containerRegistry: $(acr-registry)
  - task: Docker@2
    displayName: Build and Push Docker image
    inputs:
      command: buildAndPush
      dockerfile: $(Build.SourcesDirectory)/Dockerfile
      repository: micetro-docs
      tags: $(Build.SourceBranch)
  
- job: PublishDocs
  displayName: Publish docs
  pool: BPC-Linux-ON1
  dependsOn: BuildDocs
  
  variables:
  - group: azure-secrets

  steps:
  - checkout: none
  - task: SSH@0
    displayName: Publish docs on the web server
    inputs:
      sshEndpoint: 'ssh-docker-mice-dev'
      runOptions: 'inline'
      inline: |
        az acr login --name $(acr-registry)
        docker pull $(acr-docs-path):$(Build.SourceBranch)
        if [ "$(Build.SourceBranch)" == "latest" ]; then
          port=8080
        else
          port=$(echo $(Build.SourceBranch) | sed 's/\.//g')
        fi
        docker ps -f name=micetro-docs-$port
        if [ $(docker ps -q -f name=micetro-docs-$port) ]; then
          echo "Stopping and removing container: micetro-docs-$port"
          # Stop the container
          docker stop micetro-docs-$port
          # Remove the container
          docker rm micetro-docs-$port
        fi
        docker run -d -p $port:80 --name micetro-docs-$port $(acr-docs-path):$(Build.SourceBranch)
        docker ps
        echo $port
        if ! grep -q "location /$(Build.SourceBranch)" /etc/nginx/sites-available/docs.mice.dev; then
          block="location /$(Build.SourceBranch) { \n\tproxy_pass http://localhost:$port;\n\tproxy_set_header Host $host;\n\tproxy_set_header X-Real-IP $remote_addr;\n\tproxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n\tproxy_set_header X-Forwarded-Proto $scheme;\n}"
          sed -i "/location \/latest/i \\ $block" /etc/nginx/sites-available/docs.mice.dev
          systemctl restart nginx
        fi


  